"""Generated atlas section. Maps we run here. Not terrain."""

CARRIERS = [
 dict(id=86, key="PROC_PAIR", name="Process calc pairs",
  origin="studio process-calc / workbook module 4",
  V="Q-pairs (v, r)",
  G="isolate; Leibniz mix; rate = top.r / bottom.r",
  theta="dead isolator r=0 refuses; divisor v=0 refuses",
  outside="Inf, limits, unary D as a property of f, unlistable R",
  insight=("A rate is a ratio of two channels under one cut. Five + * / "
           "on Q send x^2 at 3 to 6. The school path uses five ops and "
           "lands on 6+h. Deleting h is not an op on Q."),
  forces=[
   dict(claim="rate(x*x,x) at 3 is 6 for seeds 1,2,1/2,10,1/3",
        check="proc_gauge_six"),
   dict(claim="pair path is 5 arithmetic ops to 6; school path 5 ops to 6+h",
        check="proc_ops_tape")],
  breaks=[
   dict(claim="rate against r=0 refuses", check="proc_dead_isolator"),
   dict(claim="(9,6) is both x^2 seed 1 and 3x seed 2 — pair is not a receipt",
        check="proc_collision")],
  useful_for=["calc pedagogy", "automatic differentiation reading"]),

 dict(id=87, key="ORIGIN_WRAP", name="Origin wrap (mechanism arithmetic)",
  origin="mathoflogic/origin rebuild",
  V="distinguishable phases of Closure(n)",
  G="co_propagate (a+b)%n ; iterate",
  theta="returns to itself",
  outside="host-free addition; unbounded Nat without a schema",
  insight=("The wrap IS Z/n. Integers are refuse-to-close. co_propagate "
           "uses host + and %. Mechanism reads a wrap; it does not birth +."),
  forces=[
   dict(claim="wrap + agrees with Peano + on {0..8}^2",
        check="origin_routes_add81")],
  breaks=[
   dict(claim="5 reads differently at n=3,7,12",
        check="origin_numeral_split"),
   dict(claim="intruder chain is not reached from 0 by S",
        check="origin_intruder")],
  useful_for=["arithmetic origin", "reification of numerals"]),

 dict(id=88, key="MODUS_MP", name="Detachment as designation-closure",
  origin="mathoflogic/modus",
  V="nine logic carriers (CL2,K3,LP,L3+,...)",
  G="MP / MT on designated set",
  theta="designated values",
  outside="MP as a law of thought; a token of the rule sitting in V",
  insight=("Detachment dies where the glut is designated. K3 gap protects. "
           "POST4 can be valid and meaningless. G is not a token in V."),
  forces=[
   dict(claim="CL2 and K3 keep MP on the full table", check="modus_k3_mp"),
   dict(claim="LP loses MP at (1/2,0)", check="modus_lp_mp_dies")],
  breaks=[
   dict(claim="reifying MP as a premise does not detach B (Carroll shape)",
        check="modus_tortoise")],
  useful_for=["inference engines", "sorites metering"]),

 dict(id=89, key="MODAL_ATLAS", name="Modal frames generated n<=3",
  origin="studio/modal + carriersets/modal, recount",
  V="listed W, listed R, atoms p,q",
  G="BOX=all successors DIA=any; filters on R",
  theta="valid on every world of every passing frame under every val",
  outside="infinite W; common knowledge as unbounded protocol; PA-completeness",
  insight=("530 frames = 2+16+512. Reflexive 69, preorder 34, equivalence 8, "
           "serial 353, GL-shape 23. 585 was a leftover string. "
           "Two S5 lookalikes split on contingency."),
  forces=[
   dict(claim="frame counts n=1..3 are 530/69/34/8/353/23",
        check="modal_frame_counts"),
   dict(claim="Löb forced on 23 GL-shaped frames; T fails at empty R",
        check="modal_gl_lob_t")],
  breaks=[
   dict(claim="two isolated loops do not see contingency; S5 blob does",
        check="modal_s5_split")],
  useful_for=["epistemic maps", "deontic D", "provability miniature"]),

 dict(id=90, key="MECH_TRAVELER", name="Seed traveler (useful pattern)",
  origin="mechanism/",
  V="reachable (x, L) under listed C, eta",
  G="v=C/(C+L+drag); L += eta*dx; vent-split; min-plus",
  theta="demand that fires reconfigure",
  outside="stars, energy=load, Navier-Stokes",
  insight=("V G theta fall out if two seeds at (0,0) with different eta "
           "are not identified."),
  forces=[
   dict(claim="arrivals L=0,2,8 over 50 cells are 50,150,450",
        check="mech_arrivals"),
   dict(claim="eta 0.1 and 0.5 after 20 ticks are not one mark",
        check="mech_two_etas")],
  breaks=[],
  useful_for=["seed mechanism"]),

 dict(id=91, key="EQ_SCALE", name="Priced equality",
  origin="studio/eq.py",
  V="listed dimensions: val, wrap, mint, slot, time",
  G="match only listed keys",
  theta="missing key or mismatch refuses",
  outside="free A=A, equivalence-kit T for free",
  insight=("(9,6) free-val merges x^2 and 3x. mint and slot refuse. "
           "Substitution on free = writes 2=0."),
  forces=[
   dict(claim="free val-eq merges; mint-eq and slot-eq refuse",
        check="eq_collision_priced")],
  breaks=[],
  useful_for=["rewrite guards"]),

 dict(id=92, key="ZN_FIELD", name="Z/n fieldish cut",
  origin="studio algebra play",
  V="{0..n-1}",
  G="add mul mod n",
  theta="no inverse",
  outside="Q as the integers, unique field",
  insight="Z/4 is not a field. n=2..12 fieldish iff prime.",
  forces=[dict(claim="fieldish Z/n for n=2..12 is {2,3,5,7,11}",
               check="zn_fieldish")],
  breaks=[],
  useful_for=["algebra origin"]),

 dict(id=93, key="S3_NONAB", name="S3 is not abelian",
  origin="break-first algebra",
  V="permutations of 3",
  G="composition",
  theta="commute-all",
  outside="all groups abelian",
  insight="One weigh. Every-group-abelian dies at |G|=6.",
  forces=[dict(claim="S3 order 6 does not commute",
               check="s3_not_abelian")],
  breaks=[],
  useful_for=["algebra pedagogy"]),

 dict(id=94, key="OP_PROGRAMS", name="Operators as programs",
  origin="studio/operators.py",
  V="whatever alphabet the program is allowed to write",
  G="the program",
  theta="write misses V",
  outside="an operator that is not a map on a listed V",
  insight=("Rate, BOX, wrap-add, min, vent are programs. Closure is "
           "the write landing. Product on V3 does not."),
  forces=[dict(claim="min closed on V3; product leaks to 1/4",
               check="op_min_closed_prod_leaks")],
  breaks=[],
  useful_for=["operator atlas"]),

 dict(id=95, key="DNA_TAPE", name="DNA complement tape",
  origin="chemistry compile",
  V="{A,C,G,T}",
  G="complement; polymerize",
  theta="base not in V; mismatch",
  outside="DNA as floor under arithmetic",
  insight="Double copy returns the strand. X refuses. Codon is a tick.",
  forces=[dict(claim="double complement returns the strand",
               check="dna_double_copy")],
  breaks=[dict(claim="X is not in V", check="dna_theta_base")],
  useful_for=["early compiled program"]),

 dict(id=96, key="PY_RUNTIME", name="Python runtime types",
  origin="CPython",
  V="runtime objects",
  G="bytecode +",
  theta="TypeError",
  outside="Python as a logic of thought",
  insight="1+'a' refuses. Dynamic V, late G, theta at runtime.",
  forces=[dict(claim="1 + 'a' raises TypeError", check="py_plus_refuses_str")],
  breaks=[],
  useful_for=["language carriers"]),

 dict(id=97, key="RUST_MOVE_MINI", name="Ownership-set miniature (Rust-shaped)",
  origin="rustc borrow",
  V="owned names",
  G="take / move",
  theta="use after move",
  outside="ownership as ontology",
  insight="Second take of x is refused. Compile-time theta on a listed set.",
  forces=[dict(claim="second take of a moved name refuses",
               check="rust_move_refuse")],
  breaks=[],
  useful_for=["language carriers"]),

 dict(id=98, key="JAVA_UNBOX_MINI", name="Null-unbox miniature (Java-shaped)",
  origin="JVM",
  V="boxed / primitive",
  G="unbox",
  theta="null",
  outside="JVM as physics",
  insight="Unbox null refuses. Different G than Python +.",
  forces=[dict(claim="unbox None refuses", check="java_null_unbox")],
  breaks=[],
  useful_for=["language carriers"]),

 dict(id=99, key="ECON_BUDGET", name="Budget constraint",
  origin="scarce cash",
  V="nonneg cash and stock",
  G="buy qty at price",
  theta="cash < price*qty",
  outside="utility as a soul",
  insight="4 at price 3 misses cash 10. 3 lands. Scarcity is theta.",
  forces=[dict(claim="overspend refuses; feasible buy lands",
               check="econ_budget")],
  breaks=[],
  useful_for=["economics miniatures"]),

 dict(id=100, key="ECON_LEDGER", name="Double-entry ledger",
  origin="bookkeeping",
  V="accounts",
  G="debit and credit",
  theta="books do not close",
  outside="money as substance",
  insight="cash -3 inventory +3 sums to 0. Same loop as vent conservation.",
  forces=[dict(claim="debit and credit close", check="econ_ledger")],
  breaks=[],
  useful_for=["economics miniatures"]),

 dict(id=101, key="GOODHART", name="Goodhart: measure becomes target",
  origin="de-reified economic models monograph",
  V="listed series S and measure M",
  G="optimize M",
  theta="M no longer tracks S",
  outside="this kernel instantiates Goodhart-as-law-of-nature",
  insight=("A compression. Once M is the target the coupling decoheres. "
           "Map of a process already running. Bound by local theta."),
  forces=[dict(claim="coupled series decouple after M is targeted",
               check="goodhart_target")],
  breaks=[],
  useful_for=["policy metrics"]),

 dict(id=102, key="HAYEK_SIGNAL", name="Price signal is not a free oracle",
  origin="Hayek compression + ghost from the monograph",
  V="local signals",
  G="aggregate via price",
  theta="scaffold load unpaid",
  outside="prices as perfect knowledge; Hayek as this kernel",
  insight="Signal 5 plus scaffold 2 is not the ghost oracle 5.",
  forces=[dict(claim="paid signal differs from zero-cost oracle",
               check="hayek_price_cost")],
  breaks=[],
  useful_for=["information process maps"]),

 dict(id=103, key="LUCAS_SLOPE", name="Fitted slope dies after policy shift",
  origin="Lucas critique miniature",
  V="listed (x,y) under a policy",
  G="fit slope; agents change rule",
  theta="old slope reused after the shift",
  outside="representative agent omniscience; DSGE as this kernel",
  insight="Slope 2 on the old cut is not slope 1 on the new cut.",
  forces=[dict(claim="old slope != new slope after rule change",
               check="lucas_slope_breaks")],
  breaks=[],
  useful_for=["policy evaluation maps"]),

 dict(id=104, key="GHOST_CLOSE", name="Closure by unpaid assumption",
  origin="monograph step 2: closure requires a new ghost",
  V="known units vs needed units",
  G="add a zero-cost unit to close",
  theta="honest known < needed",
  outside="the ghost is real",
  insight="Known 3 needed 4 does not close. Adding unpaid 1 closes. That +1 is the ghost.",
  forces=[dict(claim="system closes only after unpaid +1",
               check="ghost_zero_cost_close")],
  breaks=[],
  useful_for=["reification audit"]),
]

GENERATED = [c for c in CARRIERS if c["id"] < 95]
HYPOTHESIS = [c for c in CARRIERS if c["id"] >= 95]
